openapi: 3.0.3
info:
  title: "NeoMarket B2C: Каталог + Карточка товара"
  version: "0.1"
  description: |
    Проектируется синдикатом Forge.
    Домены: текстовый поиск, фильтры, пагинация, карточка товара, SKU, рекомендации.

paths: {}
# Здесь команды Forge описывают свои эндпоинты
